language: python
sudo: false
python: 3.5
git:
  depth: 1
cache:
  - pip: true
addons:
  apt:
    packages:
    - swig
    - libxml2-dev
    - libglpk-dev
    - glpk-utils

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip setuptools wheel
  - pip install -U memote tox

# command to run tests, e.g. python setup.py test
script: travis_wait tox -e suite
